# Create sql instance
# Create user wordpress
# Create database wordpress
# Create service account with Cloud SQL Client access
# Create secret cloudsql-instance-credentials
# kubectl create secret generic cloudsql-instance-credentials --from-file=credentials.json=./credentials.json
# Create secret wordpress-cloudsql-db-credentials
# kubectl create secret generic wordpress-cloudsql-db-credentials \
#  --from-literal=username=wordpress \
#  --from-literal=password=[YOUR_PASSWORD] \
#  --from-literal=connectionName=[INSTANCE_CONNECTION_NAME]

apiVersion: v1
kind: Service
metadata:
  namespace: itsmetommy
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: itsmetommy
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  serviceName: "wordpress"
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: wordpress
        image: wordpress:4.9.8-apache
        imagePullPolicy: IfNotPresent
        env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:3306
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-cloudsql-db-credentials
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-cloudsql-db-credentials
              key: password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-volume
          mountPath: /var/www/html
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 20
          successThreshold: 1
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        env:
          - name: CONNECTION_NAME
            valueFrom:
              secretKeyRef:
                name: wordpress-cloudsql-db-credentials
                key: connectionName
        command: ["/cloud_sql_proxy",
                  "-instances=$(CONNECTION_NAME)=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
  volumeClaimTemplates:
    - metadata:
        name: wordpress-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi